precautions = {
    "AIDS": ["Avoid unprotected sex", "Do not share needles", "Take antiretroviral medications regularly"],
    "Acne": ["Wash your face twice daily", "Avoid popping pimples", "Use non-comedogenic products"],
    "Alcoholic Hepatitis": ["Stop alcohol consumption", "Eat a balanced diet", "Follow prescribed medication"],
    "Allergy": ["Avoid allergens", "Use antihistamines", "Keep surroundings clean"],
    "Arthritis": ["Exercise regularly", "Maintain a healthy weight", "Use pain relief medication if needed"],
    "Bronchial Asthma": ["Avoid allergens", "Use inhalers as prescribed", "Practice breathing exercises"],
    "Cervical Spondylosis": ["Do neck exercises", "Use a supportive pillow", "Avoid prolonged neck strain"],
    "Chickenpox": ["Avoid scratching", "Stay hydrated", "Use calamine lotion"],
    "Chronic Cholestasis": ["Follow a low-fat diet", "Avoid alcohol", "Take liver supplements as prescribed"],
    "Common Cold": ["Stay hydrated", "Get plenty of rest", "Use steam inhalation"],
    "Dengue": ["Use mosquito repellents", "Avoid stagnant water", "Stay hydrated and rest"],
    "Diabetes": ["Monitor blood sugar regularly", "Follow a diabetic diet", "Exercise daily"],
    "Dimorphic Hemmorhoids (piles)": ["Eat high-fiber foods", "Drink lots of water", "Avoid straining during bowel movements"],
    "Drug Reaction": ["Avoid the triggering drug", "Consult a doctor", "Use prescribed antihistamines"],
    "Fungal Infection": ["Keep the area dry", "Use antifungal creams", "Avoid sharing personal items"],
    "GERD": ["Avoid spicy foods", "Eat smaller meals", "Don't lie down after eating"],
    "Gastroenteritis": ["Stay hydrated", "Eat bland foods", "Avoid dairy and caffeine"],
    "Heart Attack": ["Take aspirin", "Seek emergency care", "Avoid physical exertion"],
    "Hepatitis A": ["Rest", "Avoid alcohol", "Maintain hygiene"],
    "Hepatitis B": ["Avoid sharing personal items", "Get vaccinated", "Avoid alcohol"],
    "Hepatitis C": ["Avoid sharing needles", "Take antiviral meds", "Avoid alcohol"],
    "Hepatitis D": ["Get Hep B vaccine", "Avoid sharing needles", "Avoid alcohol"],
    "Hepatitis E": ["Drink clean water", "Maintain hygiene", "Avoid undercooked meat"],
    "Hypertension ": ["Reduce salt intake", "Exercise regularly", "Take prescribed medication"],
    "Hyperthyroidism": ["Take antithyroid meds", "Avoid iodine-rich foods", "Regular checkups"],
    "Hypoglycemia": ["Eat small frequent meals", "Carry sugary snacks", "Monitor blood sugar"],
    "Hypothyroidism": ["Take thyroid meds regularly", "Eat iodine-rich foods", "Exercise"],
    "Impetigo": ["Maintain skin hygiene", "Avoid scratching", "Use prescribed antibiotics"],
    "Jaundice": ["Rest", "Avoid fatty foods", "Hydrate well"],
    "Malaria": ["Use mosquito nets", "Take antimalarial drugs", "Avoid stagnant water"],
    "Migraine": ["Avoid loud noises", "Rest in a dark room", "Take prescribed painkillers"],
    "Osteoarthritis": ["Exercise regularly", "Maintain joint mobility", "Use hot/cold therapy"],
    "Paralysis (brain hemorrhage)": ["Seek immediate medical help", "Physiotherapy", "Take prescribed medication"],
    "Peptic Ulcer Disease": ["Avoid spicy foods", "Don't skip meals", "Use antacids"],
    "Pneumonia": ["Take antibiotics", "Rest", "Drink plenty of fluids"],
    "Psoriasis": ["Keep skin moisturized", "Avoid triggers", "Use medicated creams"],
    "Tuberculosis": ["Take full course of meds", "Cover mouth when coughing", "Maintain good nutrition"],
    "Typhoid": ["Drink clean water", "Maintain hygiene", "Take full course of antibiotics"],
    "Urinary Tract Infection": ["Drink plenty of water", "Urinate frequently", "Take antibiotics as prescribed"],
    "Varicose Veins": ["Elevate legs", "Exercise", "Avoid standing long periods"],
    "Vertigo": ["Avoid sudden head movements", "Do balance exercises", "Stay hydrated"],
}
